name: tekartik_firebase_firestore_grpc_rest
description: Firestore listen implementation over REST / gRPC
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=0.8.2'
  tekartik_firebase_firestore_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firestore_rest
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firebase_rest
    version: '>=0.7.4'
  googleapis: '>=12.0.0'
  path: ">=1.9.1"
  http: ">=1.2.0"
  grpc: ">=5.1.0"
  googleapis_auth: ">=1.4.0"
  protobuf: ">=6.0.0"

dev_dependencies:
  fixnum: ">=1.1.0"
  test: ">=1.31.0"
  dev_build: ">=1.1.8+2"
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
    version: '>=0.6.3'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.10.7'
  tekartik_firebase_firestore_test:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_test
    version: '>=0.7.4'
  tekartik_firebase_auth_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: auth_rest
  tekartik_firebase_emulator:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_emulator

resolution: workspace
