name: tekartik_firebase_firestore_rest
description: Firebase firestore rest API
version: 0.8.6
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  sembast: ">=3.7.4+3"
  uuid: '>=1.0.0'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
    version: '>=0.8.2'
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firebase_rest
    version: '>=0.7.4'
  googleapis: '>=12.0.0'
  googleapis_auth:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.2.0+2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.10.7'
  path: ">=1.9.0"
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
  http:
dev_dependencies:
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
    version: '>=0.6.3'
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  build_test: ">=0.10.3"
  tekartik_firebase_firestore_test:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_test
    version: '>=0.7.4'
  process_run: ">=1.2.1+1"
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
    version: '>=0.8.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
    version: '>=0.1.0'

resolution: workspace
